services:
  backend-gateway-web-app:
    container_name: ${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_IMAGE_NAME}
    environment:
      - App__Authentication__Key=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_AUTHENTICATION_KEY}
      - App__Writer__GrpcApiAddress=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_WRITER_GRPC_API_ADDRESS}
      - App__Writer__RestApiAddress=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_WRITER_REST_API_ADDRESS}
    networks:
      - network-backend
    depends_on:
      backend-writer-web-app:
        condition: service_started

  backend-writer-web-app:
    container_name: ${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_WRITER_WEB_APP_IMAGE_NAME}
    environment:
      - App__Authentication__Key=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_AUTHENTICATION_KEY}      
      - App__PostgreSQL__Password=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_POSTGRESQL_PASSWORD}
      - App__PostgreSQL__Port=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_POSTGRESQL_PORT}
      - App__PostgreSQL__Server=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_POSTGRESQL_SERVER}
      - App__PostgreSQL__UserId=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_POSTGRESQL_USERID}
    networks:
      - network-backend

networks:
  network-backend:
    attachable: true
