global using System.Net;
global using System.Net.Http.Json;
global using System.Security.Cryptography;
global using System.Text;
global using Ardalis.Result;
global using Ardalis.SharedKernel;
global using Makc2024.Dummy.Shared.DeepCopy;
global using Makc2024.Dummy.Shared.Event;
global using MediatR;
